### ISSUE TITLE
Error converting from BBS to Tigger

### ISSUE THREAD

**Issue by Joshuaalbert** [ratt-ru/tigger-lsm#42]
When I try to convert from BBS to Tigger I get an error.

`tigger-convert  -t BBS -o Tigger single-source.skymodel single-source.lsm`

```
Reading single-source.skymodel (BBS source catalog)
Error loading model: name 'file' is not defined
```

The contents of `single-source.skymodel` is:

```
# (Name, Type, Ra, Dec, I) = format
A, POINT, 23:58:15.43335658, +35:14:14.96586417, 1.0
```

**Comment by JSKenyon** [comment]
Could you please post your python version and the output of `pip freeze`? I seem to get an entirely different error.

**Comment by JSKenyon** [comment]
Ok, I have made a little progress on this. The issue seems to be caused by something in the declination calculation. The value should be in `(-90, 90]` degrees but when loading the BBS file above it comes out as a value over 500. This then causes the wrong code path to be executed and everything falls apart from there. For reference, the error comes from the following line of code when the contents of `header` are incorrect: https://github.com/ratt-ru/tigger-lsm/blob/a0f50a379cd14a3e80fba0b6d757e4598ac7e6b9/Tigger/Coordinates.py#L248

**Comment by JSKenyon** [comment]
OK, problem solved. The issue is the formatting of the declination value in the BBS file. It expects the d.m.s values to be delimited with periods, not colons. In the presence of colons, I believe the value with be interpreted as `hours:minutes:seconds` which gives rise to the large declination value in the header. Changing the contents of `single-source.skymodel` to:

```
# (Name, Type, Ra, Dec, I) = format
A, POINT, 23:58:15.43335658, +35.14.14.96586417, 1.0
```

resolves the issue for me. Can you confirm @Joshuaalbert? Was this human error or did a tool produce the malformed declination values? For the sake of posterity, I figured this out when I glanced at [this](https://www.astron.nl/lofarwiki/doku.php?id=public:user_software:documentation:bbs).

**Comment by Joshuaalbert** [comment]
Hi @JSKenyon thanks for spotting this. I think this BBS model was manually made. It may also explain a weird result from before. I think it's safe to close this then.
